config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/pages/home', to: 'pages#home'
  get '/pages/about', to: 'pages#about'
  get '/pages/show', to: 'articles#show'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum:300}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to articles_path(@article)
    else
      render 'new'
    end
  end

  def edit

  end

  def show

  end

  def destroy

    @article.destroy
    flash[:notice] = "Article was successfully deleted."
    redirect_to articles_path
  end

  def update

    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/welcome_controller.rb
require 'rack'

class WelcomeController < ApplicationController

  # def home
  #
  # end

  # def about
  # end


    def self.call(env)
      case env["PATH_INFO"]
      when '/' then index
      when '/about' then about
      when '/main.css' then css
      when '/blog' then blog
      else
        error
      end
    end

    def self.home
      render_view('home.html.erb')
    end

    def self.about
      render_view('about.html.erb')
    end

    def self.error
      render_view('error.html.erb', '404')
    end

    def self.render_view(page, code = '200')
      [code, {'Content-Type' => 'text/html'}, [File.read("./app/views/#{page}")]]
      # Recall, this array includes the HTTP response status code, HTTP response headers & HTTP body
    end

    def self.css
      render_static('main.css')
    end

    def self.render_static(asset)
      [200, {'Content-Type' => 'test/html'}, [File.read("./public/#{asset}")]]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="navbar">
  <ul>
    <li><%= link_to 'Home', pages_home_path %></li>
    <li><%= link_to 'Articles List', articles_path %></li>
  </ul>
</div>
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |form| %>
  <p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
    </p>
    <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<html>
  <head id="head">
    <link rel="stylesheet" href="/main.css" title="CSS" type="text/css" />
  <h1>Listing all articles</h1>
  </head>
  <div class="navbar">
    <ul>
      <li><%= link_to 'Home', pages_home_path %></li>
      <li><%= link_to "Create new article", new_article_path %></li>
    </ul>
  </div>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>
</html>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<div class="navbar">
  <ul>
    <li><%= link_to 'Home', pages_home_path %></li>
    <li><%= link_to 'Articles List', articles_path %></li>
    <li><%= link_to 'Edit', edit_article_path(@article) %></li>
    <td><%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </ul>
</div>
<p>
  Title: <%= @article.title %></p>
  <p>
    Description: <%= @article.description %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<ul>
  <li><%= msg %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplhaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'home', 'pages_home_path' %>

app/views/pages/home.html.erb
<!-- https://git.heroku.com/alpha-blog-stiehl.git -->
<!DOCTYPE html>
<html>
  <head>
      <title>Blog</title>
      <link rel="stylesheet" href="main.css" title="CSS" type="text/css" />
      <h1>Welcome!</h1>
  </head>
  <div class="navbar">
    <ul>
      <li><%= link_to 'Alpha Blog', articles_path %></li>

    </ul>
  </div>
  <body>
<!--<%= yield %> -->
  </body>

</html>